"""Build a dependency-free static portfolio from sanitized content only."""
from pathlib import Path
from html import escape as e
import json
R=Path(__file__).resolve().parents[1];D=json.loads((R/'content.json').read_text());A=R/'assets/diagrams'
DIAGRAMS={
'cyber-overview':('Cyber telemetry and distributed ingestion','Logical platform roles across capture, collection, storage and investigation',[
('PACKET PATH',[('Mirrored network traffic','Out-of-band source traffic'),('Packet broker','Capture distribution'),('Capture systems','40 Gb/s technology test bed'),('Packet storage','Capture storage / HDFS')]),
('EVENT PATH',[('Logs + flow telemetry','App / firewall / NetFlow'),('Collectors + aggregator','Telemetry collection'),('Kafka','Brokered ingestion'),('HDFS + analytics','Distributed persistence')]),
('CROSS-CUTTING CAPABILITIES',[('Distributed processing','Spark / Hadoop'),('Search + investigation','Solr / HBase / Elasticsearch'),('Collector visibility','Prometheus monitoring'),('Repeatable deployment','Ansible / cloud + host tools')])], 'Rows group platform capabilities; they do not assert one pipeline for every data source.'),
'cyber-racks':('Capture and replay across three racks','Generalized physical topology from the integration test-bed drawing',[
('CAPTURE AND REPLAY',[('Mirrored segments','Out-of-band traffic'),('Packet broker','Capture distribution'),('Capture / replay systems','Controlled traffic paths'),('Security-tool rack','IDS / IPS integrations')]),
('DATA AND MANAGEMENT FABRICS',[('Aggregation fabric','Inter-rack data connectivity'),('Rack 1','Capture + platform systems'),('Rack 2 + rack 3','Distributed platform systems'),('Management network','Server / IPMI access')])], 'Data-transfer and management networks are separate roles. Exact ports, hostnames and IPs are omitted.'),
'cyber-logs':('Log collection test environments','Same ingestion shape; distinct functional and performance configurations',[
('PERFORMANCE ENVIRONMENT',[('Producer processes','Generate / collect events'),('Aggregator','CPU + memory + local SSD'),('Kafka brokers','Partitioned topics / replication'),('HDFS','Downstream storage')]),
('FUNCTIONAL ENVIRONMENT',[('Producer processes','Exercise collection behavior'),('Aggregator + manager','Control / functional checks'),('Broker nodes','Alternate disk configuration'),('HDFS','Validate ingestion behavior')])], 'Configuration differences are design context, not a claimed throughput improvement.'),
'cyber-capture':('Packet-capture performance environment','Capture and replay roles redrawn without device or address identifiers',[
('CAPTURE TEST PATH',[('Traffic replay sources','Controlled replay input'),('Switch / packet fabric','10G / 40G test links'),('Capture hosts','NIC + software / FPGA paths'),('Persistent storage','SSD / disk / HDFS paths')]),
('INTEGRATION AND OPERATIONS',[('Security sensors','Corelight / IDS integrations'),('Host tuning','CPU / NIC / storage behavior'),('Data-transfer network','Capture / replay movement'),('Management network','Separate host access')])], '40 Gb/s describes the capture technology. Sustained end-to-end throughput is not established.'),
'cyber-gateway':('Gateway deployment footprints','Lightweight and larger deployments group the same operational responsibilities',[
('LIGHTWEIGHT FOOTPRINT',[('Traffic / telemetry input','Packet / log / flow sources'),('Collector + manager','Collection and control roles'),('Message + storage nodes','Buffering and persistence'),('Cloud integration','Hybrid connectivity / EC2')]),
('LARGER FOOTPRINT',[('Capture + log collectors','Dedicated collection roles'),('Message queue nodes','Separate buffering tier'),('Storage + master roles','Storage / active-backup roles'),('Cloud integration','Hybrid connectivity / EC2')])], 'Deployment options from a product design; published EPS/capacity targets are not treated as measured results.'),
'amorphic-context':('Amorphic cloud platform context','Team reference architecture dated 2019; not a claim of sole personal authorship',[
('APPLICATION ACCESS',[('Enterprise users','Federated / Cognito access'),('CloudFront + WAF','Static UI / access controls'),('API Gateway + Lambda','Application API tier'),('Data services','S3 / search / relational analytics')]),
('PLATFORM FOUNDATIONS',[('Private networking','Subnet and egress boundaries'),('Identity + encryption','IAM / KMS integration'),('Cloud operations','CloudWatch / CloudTrail'),('Delivery + data tools','CloudFormation / CI / Glue')])], 'Later team architecture included only as product context; it does not extend the stated CDL employment dates.'),
'migration':('Hadoop archives to cloud object storage','Migration approaches shown in the design; separate from the search-data migration',[
('STAGED APPROACH',[('HDFS / HAR source','Read archived documents'),('HAR extraction','Unpack source representation'),('Transfer + rename','Move and map object names'),('Amazon S3','Target objects')]),
('CUSTOM SPARK APPROACH',[('HDFS / HAR source','Retrieve archived documents'),('Spark migration job','Extraction + transfer'),('Rename + validate','Target mapping / validation'),('Amazon S3','Target objects')]),
('DISTCP + MAPREDUCE APPROACH',[('HAR extraction','Prepare source files'),('DistCp transfer','Distributed copy'),('MapReduce job','Rename + mapping generation'),('Amazon S3','Target objects')])], 'The source drawing compares approaches; it does not establish one chosen route for every workload.'),
'cloud-overview':('Hybrid cloud document and search platform','Application access, cloud foundations and recovery shown as distinct responsibilities',[
('APPLICATION DATA PATH',[('Legacy application','Enterprise data center'),('Hybrid connectivity','Private access + load balancer'),('Private proxy tier','Multi-AZ / autoscaling'),('S3 + search','Object storage / Elasticsearch')]),
('IDENTITY AND INFRASTRUCTURE',[('Enterprise identity','Directory / federation'),('AWS authorization','SAML → STS temporary credentials'),('Reusable provisioning','Roles / network / KMS / storage'),('Configuration','Environment parameters')]),
('RECOVERY RESPONSIBILITIES',[('Primary data + search','Production state'),('Replication + snapshots','Data copies / backup artifacts'),('Secondary region','Restore storage / recovery tier'),('Recovery automation','Provision + restore workflows')])], 'Logical composite of releases. DR results: approximately 15-minute RPO and 2-hour RTO for the delivered environment.'),
'cloud-proxy':('Private application access to S3','Proxy-farm design from the cloud migration architecture',[
('APPLICATION REQUEST',[('Existing application','Web application tier'),('Hybrid connection','Direct Connect / gateway'),('Load balancer','Distribute application traffic'),('Private proxy pool','Autoscaling across AZs')]),
('STORAGE ACCESS',[('Private proxy pool','Application integration point'),('S3 endpoint','Cloud storage access'),('Amazon S3','Target document objects'),('Infrastructure lifecycle','Provision / scale / operate')])], 'The lower row continues the storage access path; the lifecycle box is an operational responsibility.'),
'cloud-identity':('Identity across platform evolution','Two architecture stages, not one combined authentication flow',[
('EARLIER DIRECTORY-BASED ACCESS',[('Application users','Enterprise application'),('Directory + Kerberos','Authentication / ticket'),('DNS + resolver rules','Hybrid name resolution'),('Hadoop services','Solr / HBase access')]),
('LATER FEDERATED AWS ACCESS',[('Enterprise identity','Directory + federation service'),('SAML assertion','Federated authentication'),('IAM + STS','Temporary AWS credentials'),('Cloud resources','S3 / search access')])], 'Simplified trust dependencies. Exact authentication exchanges and environment names are omitted.'),
'cloud-iac':('Repeatable cloud infrastructure','Dependency groups from the landing-zone automation design',[
('COMPOSE THE PLATFORM',[('Infrastructure boundary','Environment deployment'),('Identity resources','Application / proxy roles'),('Network resources','Security-group boundaries'),('Storage + encryption','S3 and KMS resources')]),
('OPERATE CONSISTENTLY',[('Reusable IaC','CloudFormation / Terraform'),('Host configuration','Ansible workflows'),('Configuration references','Parameter Store'),('Platform consumers','Applications / operations')])], 'Boxes express dependency groups, not a strict serial API sequence.')
}
def svg(name,title,subtitle,rows,note):
 h=210+len(rows)*190;out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 {h}" role="img"><title>{e(title)}</title><desc>{e(subtitle+". "+note)}</desc><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6" fill="none" stroke="#388884" stroke-width="1.5"/></marker></defs><rect width="1440" height="{h}" rx="20" fill="#f5f7f7"/><path d="M0 8H1440" stroke="#087c75" stroke-width="16"/>']
 def text(x,y,t,size=20,weight=400,color='#1b3442'):out.append(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{e(t)}</text>')
 text(44,66,title,31,700);text(44,104,subtitle,20,color='#4e6570')
 for i,(label,nodes) in enumerate(rows):
  y=151+i*190;text(44,y,label,16,700,'#087c75')
  for j,(head,body) in enumerate(nodes):
   x=44+j*345;out.append(f'<rect x="{x}" y="{y+22}" width="312" height="106" rx="12" fill="white" stroke="#cfdddd"/><rect x="{x}" y="{y+22}" width="5" height="106" rx="2" fill="#087c75"/>');text(x+18,y+57,head,20,700);text(x+18,y+90,body,17,color='#4e6570')
   if j<3 and label not in ['CROSS-CUTTING CAPABILITIES','DATA AND MANAGEMENT FABRICS','INTEGRATION AND OPERATIONS','PLATFORM FOUNDATIONS','IDENTITY AND INFRASTRUCTURE','COMPOSE THE PLATFORM','OPERATE CONSISTENTLY']:out.append(f'<path d="M{x+315} {y+75}H{x+338}" stroke="#388884" stroke-width="2" marker-end="url(#arrow)"/>')
 text(44,h-39,note,16,color='#4e6570');out.append('</svg>');(A/(name+'.svg')).write_text('\n'.join(out))
for k,(t,s,rows,n) in DIAGRAMS.items():svg(k,t,s,rows,n)

def shell(title,description,body,base='',path=''):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(title)} | Venkata Ganji</title><meta name="description" content="{e(description)}"><meta name="theme-color" content="#153733"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:type" content="website"><link rel="canonical" href="https://offroadguy.github.io/{path}"><link rel="icon" href="{base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{base}assets/style.css?v=1.3.0"><script defer src="{base}assets/site.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="{base}index.html"><span class="monogram">VG</span> Venkata Ganji</a><nav aria-label="Primary"><a href="{base}index.html#work">Selected work</a><a href="{base}index.html#about">About</a><a href="{base}downloads/Venkata_Ganji_Resume.pdf">Resume <span aria-hidden="true">↗</span></a><a class="nav-contact" href="{D['linkedin']}">LinkedIn ↗</a></nav></header>{body}<footer><div><strong>Venkata Ganji</strong><p>AI infrastructure · Distributed systems · Production engineering</p></div><div><a href="{base}downloads/Venkata_Ganji_Case_Studies.pdf">Download case studies</a><a href="{D['linkedin']}">Connect on LinkedIn ↗</a><small>Low-resolution originals + simplified architecture views · Updated October 2026</small></div></footer><dialog id="diagram-dialog" aria-labelledby="dialog-title"><div class="dialog-toolbar"><strong id="dialog-title">Architecture diagram</strong><div><button id="zoom-out" type="button" aria-label="Zoom out">−</button><button id="zoom-in" type="button" aria-label="Zoom in">+</button><button id="close-dialog" type="button">Close ✕</button></div></div><div class="diagram-stage"><img id="dialog-image" alt=""></div></dialog></body></html>'''

def figure(id,title,base='../',caption='Sanitized logical architecture. Open the full-size view to explore the flow.'):
 return f'''<figure class="diagram"><button class="diagram-open" type="button" data-diagram="{base}assets/diagrams/{id}.svg" data-title="{e(title)}" aria-label="Expand {e(title)}"><img src="{base}assets/diagrams/{id}.svg" alt="{e(title)}" loading="lazy"><span>Explore diagram <b>⤢</b></span></button><figcaption>{e(caption)} <a href="{base}assets/diagrams/{id}.svg" target="_blank" rel="noopener">Open SVG ↗</a></figcaption></figure>'''

def listing(c):return f'''<a class="case-card {c['color']}" href="cases/{c['id']}.html"><div class="case-card-top"><span>{c['number']} / {c['category']}</span><span aria-hidden="true">↗</span></div><h3>{e(c['short'])}</h3><p>{e(c['deck'])}</p><div class="case-card-visual"><img src="assets/diagrams/{c['diagram']}.svg" alt="" loading="lazy"></div><div class="case-card-bottom"><span>{e(c['engagement'].split(' · ')[0])}</span><strong>Read the case study →</strong></div></a>'''
body='''<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">VENKATA GANJI / ENGINEERING PORTFOLIO</p><h1>AI infrastructure.<br>Distributed systems.<br><em>Production ownership.</em></h1><p class="hero-intro">'''+e(D['intro'])+'''</p><div class="actions"><a class="button" href="#work">Explore selected work <span>↓</span></a><a class="text-link" href="downloads/Venkata_Ganji_Resume.pdf">Download resume ↗</a></div><p class="hero-foot">12+ years of professional engineering · Concord, California</p></div><figure class="hero-portrait"><div class="portrait-frame"><img src="assets/venkata-ganji.jpg" alt="Venkata Ganji" width="1200" height="1800" fetchpriority="high"></div><figcaption><strong>Venkata Ganji</strong><span>AI infrastructure &amp; distributed systems</span></figcaption></figure></section><section class="impact-strip" aria-label="Selected career outcomes"><div><strong>7.0s → 1.9s</strong><span>Approximate vector-query latency · Apple</span></div><div><strong>$266K+</strong><span>Annualized Solr migration savings · Apple</span></div><div><strong>30 PB</strong><span>Total Hadoop capacity operated · Amobee/Turn</span></div></section><section class="work-section" id="work"><div class="section-intro"><div><p class="eyebrow">SELECTED WORK / FOUR ENGINEERING STORIES</p><h2>Architecture with an<br>operating story.</h2></div><p>Each case connects the problem, my contribution, the system design and the outcome. Start with GenAI for AI platform roles, or explore the data and migration work underneath.</p></div><div class="case-grid">'''+''.join(listing(c) for c in D['cases'])+'''</div></section><section class="about-section" id="about"><div><p class="eyebrow">HOW I WORK</p><h2>I follow the problem<br>across system boundaries.</h2></div><div><p>My work spans application infrastructure, distributed storage and the operational details between them. I write deployment and lifecycle tooling, diagnose performance, lead migrations and stay accountable for production behavior.</p><p>At Apple, as a contractor through Mphasis, that meant ingestion, inference and model-serving infrastructure. At Cloudwick, it included cyber telemetry, enterprise cloud migrations and large distributed-data environments.</p><a class="text-link" href="'''+D['linkedin']+'''">Connect on LinkedIn ↗</a></div></section><section class="reading-note"><strong>A note on the diagrams</strong><p>Start with the simplified architecture views, then see low-resolution previews of the original diagrams in each case study. Full-resolution originals are not offered here. Each case distinguishes my contribution, team architecture context and the scope of reported results.</p></section></main>'''
(R/'index.html').write_text(shell('AI Infrastructure & Distributed Systems',D['intro'],body))
for i,c in enumerate(D['cases']):
 metrics=''.join(f'<div><strong>{e(v)}</strong><span>{e(l)}</span></div>' for v,l in c['metrics'])
 ownership=''.join(f'<li>{e(x)}</li>' for x in c['ownership'])
 flow=''.join(f'<li><span class="step-num">{n+1:02}</span><div><h3>{e(h)}</h3><p>{e(t)}</p></div></li>' for n,(h,t) in enumerate(c['flow']))
 decisions=''.join(f'<article><h3>{e(h)}</h3><p>{e(t)}</p></article>' for h,t in c['decisions'])
 results=''.join(f'<li>{e(t)}</li>' for t in c['results'])
 supporting=''
 if c['supporting']:
  supporting='<section id="deep-dive"><p class="eyebrow">SUPPORTING VIEWS</p><h2>Go one level deeper.</h2>'+''.join(f'<details><summary>{e(title)}</summary><p>{e(desc)}</p>'+figure(id,title,caption=desc)+'</details>' for id,title,desc in c['supporting'])+'</section>'
 originals=''
 if c.get('originals'):
  cards=[]
  for o in c['originals']:
   preview='../assets/original-previews-lowres/'+o['preview']
   cards.append(f'<article class="original-card"><div class="original-preview"><img src="{preview}" alt="Low-resolution preview of {e(o["title"])}" loading="lazy"><span>LOW-RESOLUTION PORTFOLIO PREVIEW</span></div><div class="original-body"><h3>{e(o["title"])}</h3><p>{e(o["description"])}</p></div></article>')
  originals='<section id="original-diagrams"><p class="eyebrow">ORIGINAL DIAGRAMS</p><h2>A glimpse of the original diagrams.</h2><p>These low-resolution previews show the original layouts. Use the simplified architecture walkthroughs above for readable technical explanations; full-resolution original files are not offered here.</p><div class="original-grid">'+''.join(cards)+'</div></section>'
 nxt=D['cases'][(i+1)%4]
 b=f'''<main id="main"><section class="case-hero {c['color']}"><a class="back-link" href="../index.html#work">← Selected work</a><p class="eyebrow">CASE {c['number']} / {c['category']}</p><h1>{e(c['title'])}</h1><p class="case-deck">{e(c['deck'])}</p><div class="engagement"><strong>{e(c['engagement'])}</strong><span>{e(c['role'])}</span></div><div class="tags">{''.join('<span>'+e(t)+'</span>' for t in c['tags'])}</div></section><div class="case-metrics">{metrics}</div><div class="case-layout"><aside><p>IN THIS CASE</p><a href="#context">Context & ownership</a><a href="#architecture">Architecture</a><a href="#decisions">Engineering decisions</a><a href="#outcomes">Results & operations</a>{'<a href="#deep-dive">Supporting diagrams</a>' if supporting else ''}<a href="#original-diagrams">Original diagrams</a><a href="../downloads/Venkata_Ganji_Case_Studies.pdf">Download case studies ↗</a></aside><article class="case-content"><section id="context"><p class="eyebrow">THE PROBLEM</p><h2>{e(c['short'])}</h2><p>{e(c['problem'])}</p><div class="ownership"><h3>What I owned</h3><p>{e(c['summary'])}</p><ul>{ownership}</ul></div></section><section id="architecture"><p class="eyebrow">SYSTEM DESIGN</p><h2>Follow the architecture.</h2>{figure(c['diagram'],c['short'])}<ol class="flow-list">{flow}</ol></section><section id="decisions"><p class="eyebrow">ENGINEERING JUDGMENT</p><h2>The decisions behind the boxes.</h2><div class="decision-grid">{decisions}</div></section><section id="outcomes"><p class="eyebrow">DELIVERY & OPERATIONS</p><h2>What changed.</h2><ul class="results">{results}</ul><h3>The operating story</h3><p>{e(c['operations'])}</p></section>{supporting}{originals}<section class="interview"><p class="eyebrow">LET’S GO DEEPER</p><h2>Good starting points for a conversation.</h2><ul>{''.join('<li>'+e(q)+'</li>' for q in c['questions'])}</ul></section><p class="scope"><strong>Scope and attribution.</strong> {e(c['scope'])}</p><a class="next-case" href="{nxt['id']}.html"><span>Next case study</span><strong>{e(nxt['short'])} →</strong></a></article></div></main>'''
 (R/'cases'/f"{c['id']}.html").write_text(shell(c['title'],c['deck'],b,'../',f"cases/{c['id']}.html"))
(R/'404.html').write_text(shell('Page not found','Return to the engineering portfolio.','<main id="main" class="not-found"><p class="eyebrow">404</p><h1>This page has moved.</h1><a class="button" href="/">Return to portfolio →</a></main>',base='/'))
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://offroadguy.github.io/'+p+'</loc></url>' for p in ['']+[f"cases/{c['id']}.html" for c in D['cases']])+'</urlset>')
(R/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://offroadguy.github.io/sitemap.xml\n');(R/'.nojekyll').touch()
print('Built home, four case studies, supporting SVGs and metadata.')
